spring:
  application:
    name: LX-gatway # 应用名称，会在Eureka中显示
  profiles:
    active: dev  #启动服务时，服务器会自动加载的配置文件
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/, http://127.0.0.1:10001/eureka/, http://127.0.0.1:10002/eureka/