spring:
  application:
    name: dept-feign # 应用名称，会在Eureka中显示
  profiles:
    active: dev  #启动服务时，服务器会自动加载的配置文件
eureka:
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    #    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port} # DESKTOP-2MVEC12:user-service:8081：是示例的名称，instance-id是区分同一服务的不同实例的唯一标准，因此不能重复
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/, http://127.0.0.1:10001/eureka/, http://127.0.0.1:10002/eureka/

# `@FeignClient`注解修改的客户端在被代理时，都会创建一个新的Fegin.Logger实例。我们需要额外指定这个日志的级别才可以。
logging:
  level:
    com.epsilon.lx: debug
#新版配置，否则后面dashboard无法找到hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 开启feign熔断，不然不能在Hystrix-dashoard
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  command:
#    default:  # 默认全局
#      execution:
#        timeout:
#          enable: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 12000 # 设置hystrix的超时时间为6000ms，默认1000ms
#ribbon:
#  ConnectTimeout: 1000 # 连接超时时间(ms)
#  ReadTimeout: 2000 # 通信超时时间(ms)
#  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 1 # 同一实例的重试次数
